Первое задание

In [8]:
import numpy as np
arr = np.random.rand(30)
largest_5 = np.sort(arr)[-5:]
print(arr)
print(' ')
print(largest_5)

[0.8088284  0.56838862 0.03134041 0.00781582 0.45837212 0.31649634
 0.73608527 0.8447175  0.22343369 0.522854   0.66498242 0.15962594
 0.35881575 0.14925869 0.45641928 0.21724189 0.2292555  0.82819098
 0.47564316 0.11104844 0.57735761 0.49355668 0.98142437 0.84395233
 0.34448813 0.06764519 0.31110645 0.71441331 0.2345495  0.64271061]
 
[0.8088284  0.82819098 0.84395233 0.8447175  0.98142437]


Второе задание

In [10]:
jopa = np.arange(1, 17).reshape(4, 4)
print(jopa)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Третье задание

In [11]:
jopa2 = np.logspace(0, 2, 10)
print(jopa2)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


Четвертое задание

In [15]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8, 10])
corr = np.corrcoef(a, b)[0, 1]
print(a)
print(' ')
print(b)
print(' ')
print(corr)

[1 2 3 4 5]
 
[ 2  4  6  8 10]
 
0.9999999999999999


Пятое задание

In [14]:
jopa3 = np.random.rand(5, 5)
determinant = np.linalg.det(jopa3)
print(jopa3)
print(' ')
print(determinant)

[[0.75105177 0.04644412 0.26733719 0.18568786 0.83337297]
 [0.85265776 0.55292479 0.95276027 0.03810302 0.00288457]
 [0.21772887 0.63577512 0.936789   0.15049304 0.00427493]
 [0.45679315 0.3361348  0.27981246 0.30910957 0.52850063]
 [0.33539045 0.64855482 0.73713101 0.65924278 0.57146401]]
-0.027125823634387605


Шестое задание

In [17]:
jopa4 = np.arange(1, 10).reshape(3, 3)
print(jopa4)
anti_diagonal = np.fliplr(jopa4).diagonal()
print(' ')
print(anti_diagonal)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[3 5 7]


Седьмое задание

In [18]:
jopa5 = np.random.rand(5, 5)
print(jopa5)
print(' ')
indices = np.argwhere(jopa5 > 0.7)
print(indices)

[[0.62782601 0.30957417 0.91674729 0.24097107 0.78549215]
 [0.19219483 0.4464644  0.1530598  0.04632817 0.66700596]
 [0.8895659  0.96164742 0.26922928 0.22288007 0.60525634]
 [0.77903322 0.27047345 0.10603376 0.45559014 0.12085133]
 [0.86812162 0.56970055 0.37851258 0.4363663  0.14228887]]
 
[[0 2]
 [0 4]
 [2 0]
 [2 1]
 [3 0]
 [4 0]]


Восьмое задание

In [19]:
jopa6 = np.array([1, 5, 3])
jopa7 = np.array([2, 5, 1])
print(jopa6)
print(' ')
print(jopa7)
print(' ')
boolean_mask = (jopa6 == jopa7)
print(boolean_mask)

[1 5 3]
 
[2 5 1]
 
[False  True False]


Девятое задание

In [20]:
jopa8 = np.array([1, 2, 3, 4, 5])
jopa8[jopa8 % 2 == 0] = -1
print(jopa8)

[ 1 -1  3 -1  5]


Десятое задание

In [21]:
jopa9 = np.array([3.0, 4.0])
l2_normalized = jopa9 / np.linalg.norm(jopa9)
print(jopa9)
print(' ')
print(l2_normalized)

[3. 4.]
 
[0.6 0.8]
